```{r}
# Load libraries
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
```

```{r}
input_path <- "/Users/laurenstein/Desktop/pbmc_local_data/pbmc_ser_filtered_v1.rds"
filter_df <- readRDS(input_path)
```

```{r}
# Normalize for cell cycle
filter_df <- NormalizeData(filter_df)
```

```{r}
# Load cell cycle markers
load("../data/cycle.rda")

# Score cells for cell cycle
filter_df_cell <- CellCycleScoring(filter_df, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)

# View cell cycle scores and phases assigned to cells                                 
# View(filter_df_cell@meta.data)    
```

```{r}
# Identify the most variable genes
filter_df_cell<- FindVariableFeatures(filter_df_cell, 
                     selection.method = "vst",
                     nfeatures = 2000, 
                     verbose = FALSE)
		     
# Scale the counts
filter_df_cell <- ScaleData(filter_df_cell)
```

```{r}
# Perform PCA
filter_df_cell <- RunPCA(filter_df_cell)

# Plot the PCA colored by cell cycle phase
DimPlot(filter_df_cell,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")
```
No major differences due to cell cycle phase, no need to regress out

```{r}
options(future.globals.maxSize = 4000 * 1024^2)
```

```{r}
  filter_df_cell <- NormalizeData(filter_df_cell, verbose = TRUE) #Required to prevent very high expressing genes from dominating 
  filter_df_cell <- CellCycleScoring(filter_df_cell, g2m.features = g2m_genes, s.features = s_genes)
  filter_df_cell <- SCTransform(filter_df_cell, vars.to.regress = c("mitoRatio"))

```


```{r}
# These are now standard steps in the Seurat workflow for visualization and clustering
filter_df_cell <- RunPCA(filter_df_cell, verbose = FALSE)
filter_df_cell <- RunUMAP(filter_df_cell, dims = 1:10, verbose = FALSE) #Visualization

filter_df_cell <- FindNeighbors(filter_df_cell, dims = 1:10, verbose = FALSE)
filter_df_cell <- FindClusters(filter_df_cell, verbose = FALSE)
DimPlot(filter_df_cell, label = TRUE) + NoLegend()

# Single line code
# pbmc <- CreateSeuratObject(pbmc_data) %>% PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt") %>% SCTransform(vars.to.regress = "percent.mt") %>% RunPCA() %>% FindNeighbors(dims = 1:30) %>% RunUMAP(dims = 1:30) %>% FindClusters()
```

```{r}
VlnPlot(filtered_phase_pmbc, features = c("CD8A", "CD45", "GFRAL", "GDF15", "PDF", "NAG", "SBF", "NAG-1"), 
    pt.size = 0.2)
```

```{r}
# Visualize canonical marker genes on the sctransform embedding.
FeaturePlot(filtered_phase_pmbc, features = c("CD8A", "CD123", "CD11b","MARCO", "GFRAL", "GDF15", "TGF", "NOC2L"), pt.size = 0.2)
```

```{r}
# Visualize canonical marker genes on the sctransform embedding fro GRANULOCYTE.
FeaturePlot(filtered_phase_pmbc, features = c("CD16", "PTPRC", "CD93", "ITGAL", "MARCO", "CD11c", "CD24", "CD43"), pt.size = 0.2, 
    ncol = 3)
```

```{r}
# Determine metrics to plot present in seurat_integrated@meta.data
metrics <-  c("nCount_RNA", "nFeature_RNA", "S.Score", "G2M.Score", "mitoRatio")

FeaturePlot(filtered_phase_pmbc, 
            reduction = "umap", 
            features = metrics,
            pt.size = 0.4, 
            sort.cell = TRUE,
            min.cutoff = 'q10',
            label = TRUE)
```

```{r}

```

