```{r}
library(Matrix)
library(dplyr)
library(Seurat)
```

```{r}
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19/")
```

```{r}
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
dim(pbmc)
```

```{r}
metadata <- pbmc@meta.data
```



```{r}
# Add number of genes per UMI for each cell to metadata
# Create new column called log10GenesPerUMI
pbmc$log10GenesPerUMI <- log10(pbmc$nFeature_RNA) / log10(pbmc$nCount_RNA)
pbmc$log10GenesPerUMI <- pbmc@meta.data$log10GenesPerUMI
```

```{r}
# Add mitochondrial feature set
pbmc$percent.mt <- PercentageFeatureSet(pbmc, pattern = "^MT-")

#Add mitoRatio to the meta.data table
pbmc$mitoRatio <- pbmc@meta.data$percent.mt / 100
head(pbmc)
```
```{r}
pbmc@meta.data
```

```{r}
                           
# Create .RData object to load at any time
saveRDS(pbmc, file="data/pbmc_filtered_seurat.rds")
```


